esphome:
  name: esphome-pspwm
  friendly_name: esphome-pspwm
  min_version: 2026.5.3
  build_path: build/esphome-pspwm

external_components:
  - source: components

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  variant: ESP32S3
  cpu_frequency: 240MHZ
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_SPIRAM_SUPPORT: "y"
      CONFIG_SPIRAM: "y"
      CONFIG_SPIRAM_MODE_OCT: "y"
      CONFIG_SPIRAM_SPEED_80M: "y"
    version: 5.5.4
    log_level: ERROR
    components: 
      - name: esp32_ps_pwm
        path: /home/yoonki/esphome/esphome_ps_pwm/components/ps_pwm/esp32_ps_pwm
    platform_version: https://github.com/pioarduino/platform-espressif32/releases/download/55.03.38-1/platform-espressif32.zip
    source: pioarduino/framework-espidf@https://github.com/pioarduino/esp-idf/releases/download/v5.5.4/esp-idf-v5.5.4.tar.xz

logger:
  hardware_uart: USB_SERIAL_JTAG
output:
  - platform: ps_pwm
    id: test_ps_pwm
    pin_lead_a: 5
    pin_lead_b: 4
    pin_lag_a: 7
    pin_lag_b: 6
    frequency: 100000Hz

light:
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: 48
    num_leds: 1
    chipset: ws2812
    name: "Onboard LED"
    id: onboard_led

binary_sensor:
  - platform: gpio
    pin:
      number: 0
      inverted: true
      mode:
        input: true
        pullup: true
    name: "BOOT Button"
    on_press:
      - lambda: |-
          static float level = 0.0;
          level += 0.25;
          if (level > 1.0) level = 0.0;
          id(test_ps_pwm).set_level(level);
          
          auto call = id(onboard_led).turn_on();
          call.set_brightness(1.0);
          call.set_rgb(0.0, level, 1.0 - level);
          call.perform();
          
          ESP_LOGI("test", "Set PS-PWM level to %.2f, Color: R=0.00, G=%.2f, B=%.2f", level, level, 1.0 - level);
